// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLMTi4Jw4xg8aQdJnYj9qaeulARoJeiQs',
    appId: '1:236223688965:web:78f71a94401ece1ef2876c',
    messagingSenderId: '236223688965',
    projectId: 'corry-cicd-test',
    authDomain: 'corry-cicd-test.firebaseapp.com',
    storageBucket: 'corry-cicd-test.firebasestorage.app',
    measurementId: 'G-8BL7P00LEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxnFl-kD8m_w7F2VUPfZSxsM0uRLOHYp4',
    appId: '1:236223688965:android:e2f22c7afa4fce74f2876c',
    messagingSenderId: '236223688965',
    projectId: 'corry-cicd-test',
    storageBucket: 'corry-cicd-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQK2zoxPHD83HQliKM3zoh4d0rs-i_9I',
    appId: '1:236223688965:ios:f9313ab8d25904e8f2876c',
    messagingSenderId: '236223688965',
    projectId: 'corry-cicd-test',
    storageBucket: 'corry-cicd-test.firebasestorage.app',
    iosBundleId: 'com.example.practiceApp',
  );
}
